#! /usr/bin/env python3

import sys
from argparse import ArgumentParser

from g2base import ssdlog
import ginga.toolkit as ginga_toolkit


def main(options, args):
    if options.toolkit is None:
        logger.error("Please choose a GUI toolkit with -t option")

    # decide our toolkit, then import
    ginga_toolkit.use(options.toolkit)
    from g2client import g2disp_gui

    g2disp_gui.main(options, args)



# Create demo in root window for testing.
if __name__ == '__main__':

    argprs = ArgumentParser(description="Gen2 observation client GUI")
    argprs.add_argument('-d', "--config_dir", dest="config_dir",
                        default=None, metavar="DIR",
                        help="DIR containing configuration files")
    argprs.add_argument("-g", "--geometry", dest="geometry",
                        metavar="GEOM", default="-30-100",
                        help="X geometry for initial size and placement")
    argprs.add_argument("-t", "--toolkit", dest="toolkit", metavar="NAME",
                        default='qt5',
                        help="Choose GUI toolkit (gtk|qt)")
    ssdlog.addlogopts(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) != 0:
        argprs.error("incorrect number of arguments")

    main(options, args)
