#!/usr/bin/env python

import sys
from optparse import OptionParser

from g2client import g2disp

if __name__ == '__main__':

    usage = "usage: %prog [options]"
    optprs = OptionParser(usage=usage, version=('%%prog'))
    g2disp.add_options(optprs)

    (options, args) = optprs.parse_args(sys.argv[1:])

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args, no_gui)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args, no_gui)')

    else:
        cmd_ui = g2disp.CmdLineUI(options)

        g2disp.main(options, args, cmd_ui)

#END
