#! /usr/bin/env python3

import sys
from argparse import ArgumentParser

import ginga.toolkit as ginga_toolkit

from g2client import g2disp


def main(options, args):
    if options.toolkit is None:
        logger.error("Please choose a GUI toolkit with -t option")

    # decide our toolkit, then import
    ginga_toolkit.use(options.toolkit)
    from g2client import g2disp_gui

    gui = g2disp_gui.GraphicalUI(options)

    g2disp.main(options, args, gui)



# Create demo in root window for testing.
if __name__ == '__main__':

    argprs = ArgumentParser(description="Gen2 observation client GUI")
    argprs.add_argument("-g", "--geometry", dest="geometry",
                        metavar="GEOM", default="-30-100",
                        help="X geometry for initial size and placement")
    argprs.add_argument("-t", "--toolkit", dest="toolkit", metavar="NAME",
                        default='qt5',
                        help="Choose GUI toolkit (gtk|qt)")
    g2disp.add_options(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if len(args) != 0:
        argprs.error("incorrect number of arguments")

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args)')

    else:
        main(options, args)
