#! /usr/bin/env python3

import sys
from argparse import ArgumentParser

from g2client import g2disp

if __name__ == '__main__':

    optprs = ArgumentParser(description="Gen2 observation command line client")
    g2disp.add_options(optprs)

    (options, args) = optprs.parse_known_args(sys.argv[1:])

    # Are we debugging this?
    if options.debug:
        import pdb

        pdb.run('main(options, args, no_gui)')

    # Are we profiling this?
    elif options.profile:
        import profile

        print("%s profile:" % sys.argv[0])
        profile.run('main(options, args, no_gui)')

    else:
        cmd_ui = g2disp.CmdLineUI(options)

        g2disp.main(options, args, cmd_ui)
